package org.sathyasaieire.app.ui.theme

import androidx.compose.ui.graphics.Color

// Light scheme — saffron orange seed (Material You)
val SaffronPrimary = Color(0xFFC05000)
val SaffronOnPrimary = Color(0xFFFFFFFF)
val SaffronPrimaryContainer = Color(0xFFFFDBCC)
val SaffronOnPrimaryContainer = Color(0xFF3A0D00)
val SaffronSecondary = Color(0xFF7B5736)
val SaffronOnSecondary = Color(0xFFFFFFFF)
val SaffronSecondaryContainer = Color(0xFFFFDBCC)
val SaffronOnSecondaryContainer = Color(0xFF2E1502)
val SaffronTertiary = Color(0xFF545B00)
val SaffronOnTertiary = Color(0xFFFFFFFF)
val SaffronTertiaryContainer = Color(0xFFD8E35E)
val SaffronOnTertiaryContainer = Color(0xFF181B00)
val SaffronBackground = Color(0xFFFFF8F5)
val SaffronOnBackground = Color(0xFF201A18)
val SaffronSurface = Color(0xFFFFF8F5)
val SaffronOnSurface = Color(0xFF201A18)
val SaffronSurfaceVariant = Color(0xFFF5DED5)
val SaffronOnSurfaceVariant = Color(0xFF53433D)
val SaffronOutline = Color(0xFF85736D)
val SaffronOutlineVariant = Color(0xFFD8C2BB)
val SaffronError = Color(0xFFBA1A1A)
val SaffronOnError = Color(0xFFFFFFFF)
val SaffronErrorContainer = Color(0xFFFFDAD6)
val SaffronOnErrorContainer = Color(0xFF410002)
val SaffronInverseSurface = Color(0xFF362F2C)
val SaffronInverseOnSurface = Color(0xFFFBEEEB)
val SaffronInversePrimary = Color(0xFFFFB59A)

// Dark scheme
val SaffronDarkPrimary = Color(0xFFFFB59A)
val SaffronDarkOnPrimary = Color(0xFF5A1900)
val SaffronDarkPrimaryContainer = Color(0xFF7F3000)
val SaffronDarkOnPrimaryContainer = Color(0xFFFFDBCC)
val SaffronDarkSecondary = Color(0xFFE7BEAC)
val SaffronDarkOnSecondary = Color(0xFF472A1C)
val SaffronDarkSecondaryContainer = Color(0xFF5F4030)
val SaffronDarkOnSecondaryContainer = Color(0xFFFFDBCC)
val SaffronDarkTertiary = Color(0xFFBCC745)
val SaffronDarkOnTertiary = Color(0xFF2B2E00)
val SaffronDarkTertiaryContainer = Color(0xFF3D4400)
val SaffronDarkOnTertiaryContainer = Color(0xFFD8E35E)
val SaffronDarkBackground = Color(0xFF17120F)
val SaffronDarkOnBackground = Color(0xFFEEE0DA)
val SaffronDarkSurface = Color(0xFF17120F)
val SaffronDarkOnSurface = Color(0xFFEEE0DA)
val SaffronDarkSurfaceVariant = Color(0xFF53433D)
val SaffronDarkOnSurfaceVariant = Color(0xFFD8C2BB)
val SaffronDarkOutline = Color(0xFFA18C86)
val SaffronDarkOutlineVariant = Color(0xFF53433D)
val SaffronDarkError = Color(0xFFFFB4AB)
val SaffronDarkOnError = Color(0xFF690005)
val SaffronDarkErrorContainer = Color(0xFF93000A)
val SaffronDarkOnErrorContainer = Color(0xFFFFDAD6)
val SaffronDarkInverseSurface = Color(0xFFEEE0DA)
val SaffronDarkInverseOnSurface = Color(0xFF201A18)
val SaffronDarkInversePrimary = Color(0xFFC05000)
